<?php

/**
 * This is the model base class for the table "mzgtinstituciones".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtinstituciones".
 *
 * Columns in table "mzgtinstituciones" available as properties of the model,
 * followed by relations of table "mzgtinstituciones" available as properties of the model.
 *
 * @property integer $PK_MZGTINSTITUCIONES
 * @property string $MZGTINSTITUCIONES_CODIGOIES
 * @property string $MZGTINSTITUCIONES_NOMBRE
 * @property string $MZGTINSTITUCIONES_SIGLAS
 * @property integer $MZGTINSTITUCIONES_ESTADO
 *
 * @property Mzgteventos[] $mzgteventoses
 * @property Mzgtlibros[] $mzgtlibroses
 * @property Mzgtpublicaciones[] $mzgtpublicaciones
 */
abstract class BaseMzgtinstituciones extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtinstituciones';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtinstituciones|Mzgtinstituciones', $n);
	}

	public static function representingColumn() {
		return 'MZGTINSTITUCIONES_CODIGOIES';
	}

	public function rules() {
		return array(
			array('MZGTINSTITUCIONES_ESTADO', 'numerical', 'integerOnly'=>true),
			array('MZGTINSTITUCIONES_CODIGOIES, MZGTINSTITUCIONES_NOMBRE', 'length', 'max'=>255),
			array('MZGTINSTITUCIONES_SIGLAS', 'length', 'max'=>25),
			array('MZGTINSTITUCIONES_CODIGOIES, MZGTINSTITUCIONES_NOMBRE, MZGTINSTITUCIONES_SIGLAS, MZGTINSTITUCIONES_ESTADO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTINSTITUCIONES, MZGTINSTITUCIONES_CODIGOIES, MZGTINSTITUCIONES_NOMBRE, MZGTINSTITUCIONES_SIGLAS, MZGTINSTITUCIONES_ESTADO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mzgteventoses' => array(self::HAS_MANY, 'Mzgteventos', 'FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK'),
			'mzgtlibroses' => array(self::HAS_MANY, 'Mzgtlibros', 'FK1_MZGTLIBROS_INV_MZGTINSTITUCIONES_PK_'),
			'mzgtpublicaciones' => array(self::HAS_MANY, 'Mzgtpublicaciones', 'FK1_MZGTPUBLICACIONES_INV_MZGTINSTITUCIONES_PK_'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTINSTITUCIONES' => Yii::t('app', 'Pk Mzgtinstituciones'),
			'MZGTINSTITUCIONES_CODIGOIES' => Yii::t('app', 'Mzgtinstituciones Codigoies'),
			'MZGTINSTITUCIONES_NOMBRE' => Yii::t('app', 'Mzgtinstituciones Nombre'),
			'MZGTINSTITUCIONES_SIGLAS' => Yii::t('app', 'Mzgtinstituciones Siglas'),
			'MZGTINSTITUCIONES_ESTADO' => Yii::t('app', 'Mzgtinstituciones Estado'),
			'mzgteventoses' => null,
			'mzgtlibroses' => null,
			'mzgtpublicaciones' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTINSTITUCIONES', $this->PK_MZGTINSTITUCIONES);
		$criteria->compare('MZGTINSTITUCIONES_CODIGOIES', $this->MZGTINSTITUCIONES_CODIGOIES, true);
		$criteria->compare('MZGTINSTITUCIONES_NOMBRE', $this->MZGTINSTITUCIONES_NOMBRE, true);
		$criteria->compare('MZGTINSTITUCIONES_SIGLAS', $this->MZGTINSTITUCIONES_SIGLAS, true);
		$criteria->compare('MZGTINSTITUCIONES_ESTADO', $this->MZGTINSTITUCIONES_ESTADO);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}