<?php

/**
 * This is the model base class for the table "mzgtcarreras".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtcarreras".
 *
 * Columns in table "mzgtcarreras" available as properties of the model,
 * followed by relations of table "mzgtcarreras" available as properties of the model.
 *
 * @property integer $PK_MZGTCARRERAS
 * @property string $MZGTCARRERAS_NOMBRE
 * @property string $MZGTCARRERAS_BANNER
 * @property integer $MZGTCARRERAS_ESTADO
 *
 * @property Mzgtbancoautores[] $mzgtbancoautores
 * @property Mzgtdepartamentos[] $mzgtdepartamentoses
 */
abstract class BaseMzgtcarreras extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtcarreras';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtcarreras|Mzgtcarrerases', $n);
	}

	public static function representingColumn() {
		return 'MZGTCARRERAS_NOMBRE';
	}

	public function rules() {
		return array(
			array('MZGTCARRERAS_NOMBRE, MZGTCARRERAS_ESTADO', 'required'),
			array('MZGTCARRERAS_ESTADO', 'numerical', 'integerOnly'=>true),
			array('MZGTCARRERAS_NOMBRE', 'length', 'max'=>200),
			array('MZGTCARRERAS_BANNER', 'length', 'max'=>20),
			array('MZGTCARRERAS_BANNER', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTCARRERAS, MZGTCARRERAS_NOMBRE, MZGTCARRERAS_BANNER, MZGTCARRERAS_ESTADO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mzgtbancoautores' => array(self::MANY_MANY, 'Mzgtbancoautores', 'mzgtbancoautores_carreras(PK_MZGTCARRERAS, PK_MZGTBANCOAUTORES)'),
			'mzgtdepartamentoses' => array(self::MANY_MANY, 'Mzgtdepartamentos', 'mzgtdepartamentos_carreras(PK_MZGTCARRERAS, PK_MZGTDEPARTAMENTOS)'),
		);
	}

	public function pivotModels() {
		return array(
			'mzgtbancoautores' => 'MzgtbancoautoresCarreras',
			'mzgtdepartamentoses' => 'MzgtdepartamentosCarreras',
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTCARRERAS' => Yii::t('app', 'Pk Mzgtcarreras'),
			'MZGTCARRERAS_NOMBRE' => Yii::t('app', 'Mzgtcarreras Nombre'),
			'MZGTCARRERAS_BANNER' => Yii::t('app', 'Mzgtcarreras Banner'),
			'MZGTCARRERAS_ESTADO' => Yii::t('app', 'Mzgtcarreras Estado'),
			'mzgtbancoautores' => null,
			'mzgtdepartamentoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTCARRERAS', $this->PK_MZGTCARRERAS);
		$criteria->compare('MZGTCARRERAS_NOMBRE', $this->MZGTCARRERAS_NOMBRE, true);
		$criteria->compare('MZGTCARRERAS_BANNER', $this->MZGTCARRERAS_BANNER, true);
		$criteria->compare('MZGTCARRERAS_ESTADO', $this->MZGTCARRERAS_ESTADO);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}