<?php

/**
 * This is the model base class for the table "mzgtbancoautores".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtbancoautores".
 *
 * Columns in table "mzgtbancoautores" available as properties of the model,
 * followed by relations of table "mzgtbancoautores" available as properties of the model.
 *
 * @property integer $PK_MZGTBANCOAUTORES
 * @property string $MZGTBANCOAUTORES_TRATO
 * @property string $MZGTBANCOAUTORES_APELLIDO_PATERNO
 * @property string $MZGTBANCOAUTORES_APELLIDO_MATERNO
 * @property string $MZGTBANCOAUTORES_PRIMER_NOMBRE
 * @property string $MZGTBANCOAUTORES_SEGUNDO_NOMBRE
 * @property string $MZGTBANCOAUTORES_TIPODOCUMENTO
 * @property string $MZGTBANCOAUTORES_CEDULA
 * @property integer $FK1_MZGTBANCOAUTORES_INV_MZGTINSTITUCIONES_PK
 * @property string $MZGTBANCOAUTORES_PAIS
 * @property string $MZGTBANCOAUTORES_CODIGO
 * @property string $MZGTBANCOAUTORES_DEPARTAMENTO_CENTRO
 *
 * @property Mzgtpublicaciones[] $mzgtpublicaciones
 * @property Mzgtlibros[] $mzgtlibroses
 * @property Mzgtcarreras[] $mzgtcarrerases
 */
abstract class BaseMzgtbancoautores extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtbancoautores';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtbancoautores|Mzgtbancoautores', $n);
	}

	public static function representingColumn() {
		return 'MZGTBANCOAUTORES_TRATO';
	}

	public function rules() {
		return array(
			array('FK1_MZGTBANCOAUTORES_INV_MZGTINSTITUCIONES_PK', 'required'),
			array('FK1_MZGTBANCOAUTORES_INV_MZGTINSTITUCIONES_PK', 'numerical', 'integerOnly'=>true),
			array('MZGTBANCOAUTORES_TRATO, MZGTBANCOAUTORES_TIPODOCUMENTO', 'length', 'max'=>100),
			array('MZGTBANCOAUTORES_APELLIDO_PATERNO, MZGTBANCOAUTORES_APELLIDO_MATERNO, MZGTBANCOAUTORES_PRIMER_NOMBRE, MZGTBANCOAUTORES_SEGUNDO_NOMBRE, MZGTBANCOAUTORES_CEDULA, MZGTBANCOAUTORES_PAIS, MZGTBANCOAUTORES_CODIGO', 'length', 'max'=>255),
			array('MZGTBANCOAUTORES_DEPARTAMENTO_CENTRO', 'length', 'max'=>300),
			array('MZGTBANCOAUTORES_TRATO, MZGTBANCOAUTORES_APELLIDO_PATERNO, MZGTBANCOAUTORES_APELLIDO_MATERNO, MZGTBANCOAUTORES_PRIMER_NOMBRE, MZGTBANCOAUTORES_SEGUNDO_NOMBRE, MZGTBANCOAUTORES_TIPODOCUMENTO, MZGTBANCOAUTORES_CEDULA, MZGTBANCOAUTORES_PAIS, MZGTBANCOAUTORES_CODIGO, MZGTBANCOAUTORES_DEPARTAMENTO_CENTRO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTBANCOAUTORES, MZGTBANCOAUTORES_TRATO, MZGTBANCOAUTORES_APELLIDO_PATERNO, MZGTBANCOAUTORES_APELLIDO_MATERNO, MZGTBANCOAUTORES_PRIMER_NOMBRE, MZGTBANCOAUTORES_SEGUNDO_NOMBRE, MZGTBANCOAUTORES_TIPODOCUMENTO, MZGTBANCOAUTORES_CEDULA, FK1_MZGTBANCOAUTORES_INV_MZGTINSTITUCIONES_PK, MZGTBANCOAUTORES_PAIS, MZGTBANCOAUTORES_CODIGO, MZGTBANCOAUTORES_DEPARTAMENTO_CENTRO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mzgtpublicaciones' => array(self::MANY_MANY, 'Mzgtpublicaciones', 'mzgtautores(PK_MZGTBANCOAUTORES, PK_MZGTPUBLICACIONES)'),
			'mzgtlibroses' => array(self::MANY_MANY, 'Mzgtlibros', 'mzgtautoreslibros(PK_MZGTBANCOAUTORES, PK_MZGTLIBROS)'),
			'mzgtcarrerases' => array(self::MANY_MANY, 'Mzgtcarreras', 'mzgtbancoautores_carreras(PK_MZGTBANCOAUTORES, PK_MZGTCARRERAS)'),
		);
	}

	public function pivotModels() {
		return array(
			'mzgtpublicaciones' => 'Mzgtautores',
			'mzgtlibroses' => 'Mzgtautoreslibros',
			'mzgtcarrerases' => 'MzgtbancoautoresCarreras',
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTBANCOAUTORES' => Yii::t('app', 'Pk Mzgtbancoautores'),
			'MZGTBANCOAUTORES_TRATO' => Yii::t('app', 'Mzgtbancoautores Trato'),
			'MZGTBANCOAUTORES_APELLIDO_PATERNO' => Yii::t('app', 'Mzgtbancoautores Apellido Paterno'),
			'MZGTBANCOAUTORES_APELLIDO_MATERNO' => Yii::t('app', 'Mzgtbancoautores Apellido Materno'),
			'MZGTBANCOAUTORES_PRIMER_NOMBRE' => Yii::t('app', 'Mzgtbancoautores Primer Nombre'),
			'MZGTBANCOAUTORES_SEGUNDO_NOMBRE' => Yii::t('app', 'Mzgtbancoautores Segundo Nombre'),
			'MZGTBANCOAUTORES_TIPODOCUMENTO' => Yii::t('app', 'Mzgtbancoautores Tipodocumento'),
			'MZGTBANCOAUTORES_CEDULA' => Yii::t('app', 'Mzgtbancoautores Cedula'),
			'FK1_MZGTBANCOAUTORES_INV_MZGTINSTITUCIONES_PK' => Yii::t('app', 'Fk1 Mzgtbancoautores Inv Mzgtinstituciones Pk'),
			'MZGTBANCOAUTORES_PAIS' => Yii::t('app', 'Mzgtbancoautores Pais'),
			'MZGTBANCOAUTORES_CODIGO' => Yii::t('app', 'Mzgtbancoautores Codigo'),
			'MZGTBANCOAUTORES_DEPARTAMENTO_CENTRO' => Yii::t('app', 'Mzgtbancoautores Departamento Centro'),
			'mzgtpublicaciones' => null,
			'mzgtlibroses' => null,
			'mzgtcarrerases' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTBANCOAUTORES', $this->PK_MZGTBANCOAUTORES);
		$criteria->compare('MZGTBANCOAUTORES_TRATO', $this->MZGTBANCOAUTORES_TRATO, true);
		$criteria->compare('MZGTBANCOAUTORES_APELLIDO_PATERNO', $this->MZGTBANCOAUTORES_APELLIDO_PATERNO, true);
		$criteria->compare('MZGTBANCOAUTORES_APELLIDO_MATERNO', $this->MZGTBANCOAUTORES_APELLIDO_MATERNO, true);
		$criteria->compare('MZGTBANCOAUTORES_PRIMER_NOMBRE', $this->MZGTBANCOAUTORES_PRIMER_NOMBRE, true);
		$criteria->compare('MZGTBANCOAUTORES_SEGUNDO_NOMBRE', $this->MZGTBANCOAUTORES_SEGUNDO_NOMBRE, true);
		$criteria->compare('MZGTBANCOAUTORES_TIPODOCUMENTO', $this->MZGTBANCOAUTORES_TIPODOCUMENTO, true);
		$criteria->compare('MZGTBANCOAUTORES_CEDULA', $this->MZGTBANCOAUTORES_CEDULA, true);
		$criteria->compare('FK1_MZGTBANCOAUTORES_INV_MZGTINSTITUCIONES_PK', $this->FK1_MZGTBANCOAUTORES_INV_MZGTINSTITUCIONES_PK);
		$criteria->compare('MZGTBANCOAUTORES_PAIS', $this->MZGTBANCOAUTORES_PAIS, true);
		$criteria->compare('MZGTBANCOAUTORES_CODIGO', $this->MZGTBANCOAUTORES_CODIGO, true);
		$criteria->compare('MZGTBANCOAUTORES_DEPARTAMENTO_CENTRO', $this->MZGTBANCOAUTORES_DEPARTAMENTO_CENTRO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}