<?php

/**
 * This is the model base class for the table "mzgtconsultorias".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtconsultorias".
 *
 * Columns in table "mzgtconsultorias" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTCONSULTORIAS
 * @property integer $FK1_MZGTCONSULTORIAS_INV_MZGTINSTITUCIONES_PK
 * @property integer $FK2_MZGTCONSULTORIAS_INV_MZGTCINEAMPLI_PK
 * @property integer $FK3_MZGTCONSULTORIAS_INV_MZGTCINEESPC_PK
 * @property string $MZGTCONSULTORIAS_NOMBRE
 * @property string $MZGTCONSULTORIAS_ENTIDAD
 * @property string $MZGTCONSULTORIAS_FECHAINICIO
 * @property string $MZGTCONSULTORIAS_FECHAFIN
 * @property string $MZGTCONSULTORIAS_ALCANCE
 * @property string $MZGTCONSULTORIAS_MONTO
 *
 */
abstract class BaseMzgtconsultorias extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtconsultorias';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtconsultorias|Mzgtconsultoriases', $n);
	}

	public static function representingColumn() {
		return 'MZGTCONSULTORIAS_NOMBRE';
	}

	public function rules() {
		return array(
			array('FK1_MZGTCONSULTORIAS_INV_MZGTINSTITUCIONES_PK, FK2_MZGTCONSULTORIAS_INV_MZGTCINEAMPLI_PK, FK3_MZGTCONSULTORIAS_INV_MZGTCINEESPC_PK', 'numerical', 'integerOnly'=>true),
			array('MZGTCONSULTORIAS_NOMBRE, MZGTCONSULTORIAS_ENTIDAD, MZGTCONSULTORIAS_ALCANCE, MZGTCONSULTORIAS_MONTO', 'length', 'max'=>255),
			array('MZGTCONSULTORIAS_FECHAINICIO, MZGTCONSULTORIAS_FECHAFIN', 'safe'),
			array('FK1_MZGTCONSULTORIAS_INV_MZGTINSTITUCIONES_PK, FK2_MZGTCONSULTORIAS_INV_MZGTCINEAMPLI_PK, FK3_MZGTCONSULTORIAS_INV_MZGTCINEESPC_PK, MZGTCONSULTORIAS_NOMBRE, MZGTCONSULTORIAS_ENTIDAD, MZGTCONSULTORIAS_FECHAINICIO, MZGTCONSULTORIAS_FECHAFIN, MZGTCONSULTORIAS_ALCANCE, MZGTCONSULTORIAS_MONTO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTCONSULTORIAS, FK1_MZGTCONSULTORIAS_INV_MZGTINSTITUCIONES_PK, FK2_MZGTCONSULTORIAS_INV_MZGTCINEAMPLI_PK, FK3_MZGTCONSULTORIAS_INV_MZGTCINEESPC_PK, MZGTCONSULTORIAS_NOMBRE, MZGTCONSULTORIAS_ENTIDAD, MZGTCONSULTORIAS_FECHAINICIO, MZGTCONSULTORIAS_FECHAFIN, MZGTCONSULTORIAS_ALCANCE, MZGTCONSULTORIAS_MONTO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTCONSULTORIAS' => Yii::t('app', 'Pk Mzgtconsultorias'),
			'FK1_MZGTCONSULTORIAS_INV_MZGTINSTITUCIONES_PK' => Yii::t('app', 'Fk1 Mzgtconsultorias Inv Mzgtinstituciones Pk'),
			'FK2_MZGTCONSULTORIAS_INV_MZGTCINEAMPLI_PK' => Yii::t('app', 'Fk2 Mzgtconsultorias Inv Mzgtcineampli Pk'),
			'FK3_MZGTCONSULTORIAS_INV_MZGTCINEESPC_PK' => Yii::t('app', 'Fk3 Mzgtconsultorias Inv Mzgtcineespc Pk'),
			'MZGTCONSULTORIAS_NOMBRE' => Yii::t('app', 'Mzgtconsultorias Nombre'),
			'MZGTCONSULTORIAS_ENTIDAD' => Yii::t('app', 'Mzgtconsultorias Entidad'),
			'MZGTCONSULTORIAS_FECHAINICIO' => Yii::t('app', 'Mzgtconsultorias Fechainicio'),
			'MZGTCONSULTORIAS_FECHAFIN' => Yii::t('app', 'Mzgtconsultorias Fechafin'),
			'MZGTCONSULTORIAS_ALCANCE' => Yii::t('app', 'Mzgtconsultorias Alcance'),
			'MZGTCONSULTORIAS_MONTO' => Yii::t('app', 'Mzgtconsultorias Monto'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTCONSULTORIAS', $this->PK_MZGTCONSULTORIAS);
		$criteria->compare('FK1_MZGTCONSULTORIAS_INV_MZGTINSTITUCIONES_PK', $this->FK1_MZGTCONSULTORIAS_INV_MZGTINSTITUCIONES_PK);
		$criteria->compare('FK2_MZGTCONSULTORIAS_INV_MZGTCINEAMPLI_PK', $this->FK2_MZGTCONSULTORIAS_INV_MZGTCINEAMPLI_PK);
		$criteria->compare('FK3_MZGTCONSULTORIAS_INV_MZGTCINEESPC_PK', $this->FK3_MZGTCONSULTORIAS_INV_MZGTCINEESPC_PK);
		$criteria->compare('MZGTCONSULTORIAS_NOMBRE', $this->MZGTCONSULTORIAS_NOMBRE, true);
		$criteria->compare('MZGTCONSULTORIAS_ENTIDAD', $this->MZGTCONSULTORIAS_ENTIDAD, true);
		$criteria->compare('MZGTCONSULTORIAS_FECHAINICIO', $this->MZGTCONSULTORIAS_FECHAINICIO, true);
		$criteria->compare('MZGTCONSULTORIAS_FECHAFIN', $this->MZGTCONSULTORIAS_FECHAFIN, true);
		$criteria->compare('MZGTCONSULTORIAS_ALCANCE', $this->MZGTCONSULTORIAS_ALCANCE, true);
		$criteria->compare('MZGTCONSULTORIAS_MONTO', $this->MZGTCONSULTORIAS_MONTO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}