<?php

/**
 * This is the model base class for the table "mzgtautores".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtautores".
 *
 * Columns in table "mzgtautores" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTPUBLICACIONES
 * @property integer $PK_MZGTBANCOAUTORES
 *
 */
abstract class BaseMzgtautores extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtautores';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtautores|Mzgtautores', $n);
	}

	public static function representingColumn() {
		return 'PK_MZGTPUBLICACIONES';
	}

	public function rules() {
		return array(
			array('PK_MZGTPUBLICACIONES, PK_MZGTBANCOAUTORES', 'required'),
			array('PK_MZGTPUBLICACIONES, PK_MZGTBANCOAUTORES', 'numerical', 'integerOnly'=>true),
			array('PK_MZGTPUBLICACIONES, PK_MZGTBANCOAUTORES', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTPUBLICACIONES' => Yii::t('app', 'Pk Mzgtpublicaciones'),
			'PK_MZGTBANCOAUTORES' => Yii::t('app', 'Pk Mzgtbancoautores'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTPUBLICACIONES', $this->PK_MZGTPUBLICACIONES);
		$criteria->compare('PK_MZGTBANCOAUTORES', $this->PK_MZGTBANCOAUTORES);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}