<?php

/**
 * This is the model base class for the table "mzgteventos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgteventos".
 *
 * Columns in table "mzgteventos" available as properties of the model,
 * followed by relations of table "mzgteventos" available as properties of the model.
 *
 * @property integer $PK_MZGTEVENTOS
 * @property integer $FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK
 * @property integer $FK2_MZGTEVENTOS_INV_MZGTALCANCES_PK
 * @property integer $FK3_MZGTEVENTOS_INV_MZGTTIPOSEVENTOS_PK
 * @property integer $FK4_MZGTEVENTOS_INV_MZGTPROYECTOS_PK
 * @property string $MZGTEVENTOS_NOMBRE
 * @property string $MZGTEVENTOS_FECHAINICIO
 * @property string $MZGTEVENTOS_FECHAFIN
 * @property string $MZGTEVENTOS_CARRERA
 * @property string $MZGTEVENTOS_DEPARTAMENTO
 * @property string $MZGTEVENTOS_EVIDENCIAS
 * @property integer $FK5_MZGTEVENTOS_INV_MZGTPERSONAS_PK
 * @property string $MZGTEVENTOS_FECHAREGISTRO
 *
 * @property Mzgtpersonas $fK5MZGTEVENTOSINVMZGTPERSONASPK
 * @property Mzgtinstituciones $fK1MZGTEVENTOSINVMZGTINSTITUCIONESPK
 * @property Mzgtalcances $fK2MZGTEVENTOSINVMZGTALCANCESPK
 * @property Mzgttiposeventos $fK3MZGTEVENTOSINVMZGTTIPOSEVENTOSPK
 * @property Mzgtproyectos $fK4MZGTEVENTOSINVMZGTPROYECTOSPK
 */
abstract class BaseMzgteventos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgteventos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgteventos|Mzgteventoses', $n);
	}

	public static function representingColumn() {
		return 'MZGTEVENTOS_NOMBRE';
	}

	public function rules() {
		return array(
			array('FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK, FK2_MZGTEVENTOS_INV_MZGTALCANCES_PK, FK3_MZGTEVENTOS_INV_MZGTTIPOSEVENTOS_PK, FK4_MZGTEVENTOS_INV_MZGTPROYECTOS_PK, FK5_MZGTEVENTOS_INV_MZGTPERSONAS_PK', 'numerical', 'integerOnly'=>true),
			array('MZGTEVENTOS_NOMBRE, MZGTEVENTOS_CARRERA, MZGTEVENTOS_DEPARTAMENTO, MZGTEVENTOS_EVIDENCIAS', 'length', 'max'=>255),
			array('MZGTEVENTOS_FECHAINICIO, MZGTEVENTOS_FECHAFIN, MZGTEVENTOS_FECHAREGISTRO', 'safe'),
			array('FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK, FK2_MZGTEVENTOS_INV_MZGTALCANCES_PK, FK3_MZGTEVENTOS_INV_MZGTTIPOSEVENTOS_PK, FK4_MZGTEVENTOS_INV_MZGTPROYECTOS_PK, MZGTEVENTOS_NOMBRE, MZGTEVENTOS_FECHAINICIO, MZGTEVENTOS_FECHAFIN, MZGTEVENTOS_CARRERA, MZGTEVENTOS_DEPARTAMENTO, MZGTEVENTOS_EVIDENCIAS, FK5_MZGTEVENTOS_INV_MZGTPERSONAS_PK, MZGTEVENTOS_FECHAREGISTRO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTEVENTOS, FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK, FK2_MZGTEVENTOS_INV_MZGTALCANCES_PK, FK3_MZGTEVENTOS_INV_MZGTTIPOSEVENTOS_PK, FK4_MZGTEVENTOS_INV_MZGTPROYECTOS_PK, MZGTEVENTOS_NOMBRE, MZGTEVENTOS_FECHAINICIO, MZGTEVENTOS_FECHAFIN, MZGTEVENTOS_CARRERA, MZGTEVENTOS_DEPARTAMENTO, MZGTEVENTOS_EVIDENCIAS, FK5_MZGTEVENTOS_INV_MZGTPERSONAS_PK, MZGTEVENTOS_FECHAREGISTRO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fK5MZGTEVENTOSINVMZGTPERSONASPK' => array(self::BELONGS_TO, 'Mzgtpersonas', 'FK5_MZGTEVENTOS_INV_MZGTPERSONAS_PK'),
			'fK1MZGTEVENTOSINVMZGTINSTITUCIONESPK' => array(self::BELONGS_TO, 'Mzgtinstituciones', 'FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK'),
			'fK2MZGTEVENTOSINVMZGTALCANCESPK' => array(self::BELONGS_TO, 'Mzgtalcances', 'FK2_MZGTEVENTOS_INV_MZGTALCANCES_PK'),
			'fK3MZGTEVENTOSINVMZGTTIPOSEVENTOSPK' => array(self::BELONGS_TO, 'Mzgttiposeventos', 'FK3_MZGTEVENTOS_INV_MZGTTIPOSEVENTOS_PK'),
			'fK4MZGTEVENTOSINVMZGTPROYECTOSPK' => array(self::BELONGS_TO, 'Mzgtproyectos', 'FK4_MZGTEVENTOS_INV_MZGTPROYECTOS_PK'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTEVENTOS' => Yii::t('app', 'Pk Mzgteventos'),
			'FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK' => null,
			'FK2_MZGTEVENTOS_INV_MZGTALCANCES_PK' => null,
			'FK3_MZGTEVENTOS_INV_MZGTTIPOSEVENTOS_PK' => null,
			'FK4_MZGTEVENTOS_INV_MZGTPROYECTOS_PK' => null,
			'MZGTEVENTOS_NOMBRE' => Yii::t('app', 'Mzgteventos Nombre'),
			'MZGTEVENTOS_FECHAINICIO' => Yii::t('app', 'Mzgteventos Fechainicio'),
			'MZGTEVENTOS_FECHAFIN' => Yii::t('app', 'Mzgteventos Fechafin'),
			'MZGTEVENTOS_CARRERA' => Yii::t('app', 'Mzgteventos Carrera'),
			'MZGTEVENTOS_DEPARTAMENTO' => Yii::t('app', 'Mzgteventos Departamento'),
			'MZGTEVENTOS_EVIDENCIAS' => Yii::t('app', 'Mzgteventos Evidencias'),
			'FK5_MZGTEVENTOS_INV_MZGTPERSONAS_PK' => null,
			'MZGTEVENTOS_FECHAREGISTRO' => Yii::t('app', 'Mzgteventos Fecharegistro'),
			'fK5MZGTEVENTOSINVMZGTPERSONASPK' => null,
			'fK1MZGTEVENTOSINVMZGTINSTITUCIONESPK' => null,
			'fK2MZGTEVENTOSINVMZGTALCANCESPK' => null,
			'fK3MZGTEVENTOSINVMZGTTIPOSEVENTOSPK' => null,
			'fK4MZGTEVENTOSINVMZGTPROYECTOSPK' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTEVENTOS', $this->PK_MZGTEVENTOS);
		$criteria->compare('FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK', $this->FK1_MZGTEVENTOS_INV_MZGTINSTITUCIONES_PK);
		$criteria->compare('FK2_MZGTEVENTOS_INV_MZGTALCANCES_PK', $this->FK2_MZGTEVENTOS_INV_MZGTALCANCES_PK);
		$criteria->compare('FK3_MZGTEVENTOS_INV_MZGTTIPOSEVENTOS_PK', $this->FK3_MZGTEVENTOS_INV_MZGTTIPOSEVENTOS_PK);
		$criteria->compare('FK4_MZGTEVENTOS_INV_MZGTPROYECTOS_PK', $this->FK4_MZGTEVENTOS_INV_MZGTPROYECTOS_PK);
		$criteria->compare('MZGTEVENTOS_NOMBRE', $this->MZGTEVENTOS_NOMBRE, true);
		$criteria->compare('MZGTEVENTOS_FECHAINICIO', $this->MZGTEVENTOS_FECHAINICIO, true);
		$criteria->compare('MZGTEVENTOS_FECHAFIN', $this->MZGTEVENTOS_FECHAFIN, true);
		$criteria->compare('MZGTEVENTOS_CARRERA', $this->MZGTEVENTOS_CARRERA, true);
		$criteria->compare('MZGTEVENTOS_DEPARTAMENTO', $this->MZGTEVENTOS_DEPARTAMENTO, true);
		$criteria->compare('MZGTEVENTOS_EVIDENCIAS', $this->MZGTEVENTOS_EVIDENCIAS, true);
		$criteria->compare('FK5_MZGTEVENTOS_INV_MZGTPERSONAS_PK', $this->FK5_MZGTEVENTOS_INV_MZGTPERSONAS_PK);
		$criteria->compare('MZGTEVENTOS_FECHAREGISTRO', $this->MZGTEVENTOS_FECHAREGISTRO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}