<?php

/**
 * This is the model base class for the table "mzgtlineasinvestigacion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtlineasinvestigacion".
 *
 * Columns in table "mzgtlineasinvestigacion" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTLINEASINVESTIGACION
 * @property string $MZGTLINEASINVESTIGACION_DESCRIPCION
 * @property string $MZGTLINEASINVESTIGACION_CODIGO
 *
 */
abstract class BaseMzgtlineasinvestigacion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtlineasinvestigacion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtlineasinvestigacion|Mzgtlineasinvestigacions', $n);
	}

	public static function representingColumn() {
		return 'MZGTLINEASINVESTIGACION_DESCRIPCION';
	}

	public function rules() {
		return array(
			array('MZGTLINEASINVESTIGACION_DESCRIPCION', 'length', 'max'=>255),
			array('MZGTLINEASINVESTIGACION_CODIGO', 'length', 'max'=>50),
			array('MZGTLINEASINVESTIGACION_DESCRIPCION, MZGTLINEASINVESTIGACION_CODIGO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTLINEASINVESTIGACION, MZGTLINEASINVESTIGACION_DESCRIPCION, MZGTLINEASINVESTIGACION_CODIGO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTLINEASINVESTIGACION' => Yii::t('app', 'Pk Mzgtlineasinvestigacion'),
			'MZGTLINEASINVESTIGACION_DESCRIPCION' => Yii::t('app', 'Mzgtlineasinvestigacion Descripcion'),
			'MZGTLINEASINVESTIGACION_CODIGO' => Yii::t('app', 'Mzgtlineasinvestigacion Codigo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTLINEASINVESTIGACION', $this->PK_MZGTLINEASINVESTIGACION);
		$criteria->compare('MZGTLINEASINVESTIGACION_DESCRIPCION', $this->MZGTLINEASINVESTIGACION_DESCRIPCION, true);
		$criteria->compare('MZGTLINEASINVESTIGACION_CODIGO', $this->MZGTLINEASINVESTIGACION_CODIGO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}