<?php

/**
 * This is the model base class for the table "mzgtcampamplioscine".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtcampamplioscine".
 *
 * Columns in table "mzgtcampamplioscine" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTCAMPAMPLIOSCINE
 * @property string $MZGTCAMPAMPLIOSCINE_NOMBRE
 * @property string $MZGTCAMPAMPLIOSCINE_CODIGO
 *
 */
abstract class BaseMzgtcampamplioscine extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtcampamplioscine';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtcampamplioscine|Mzgtcampamplioscines', $n);
	}

	public static function representingColumn() {
		return 'MZGTCAMPAMPLIOSCINE_NOMBRE';
	}

	public function rules() {
		return array(
			array('MZGTCAMPAMPLIOSCINE_NOMBRE, MZGTCAMPAMPLIOSCINE_CODIGO', 'length', 'max'=>255),
			array('MZGTCAMPAMPLIOSCINE_NOMBRE, MZGTCAMPAMPLIOSCINE_CODIGO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTCAMPAMPLIOSCINE, MZGTCAMPAMPLIOSCINE_NOMBRE, MZGTCAMPAMPLIOSCINE_CODIGO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTCAMPAMPLIOSCINE' => Yii::t('app', 'Pk Mzgtcampamplioscine'),
			'MZGTCAMPAMPLIOSCINE_NOMBRE' => Yii::t('app', 'Mzgtcampamplioscine Nombre'),
			'MZGTCAMPAMPLIOSCINE_CODIGO' => Yii::t('app', 'Mzgtcampamplioscine Codigo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTCAMPAMPLIOSCINE', $this->PK_MZGTCAMPAMPLIOSCINE);
		$criteria->compare('MZGTCAMPAMPLIOSCINE_NOMBRE', $this->MZGTCAMPAMPLIOSCINE_NOMBRE, true);
		$criteria->compare('MZGTCAMPAMPLIOSCINE_CODIGO', $this->MZGTCAMPAMPLIOSCINE_CODIGO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}