<?php

/**
 * This is the model base class for the table "mzgttiposeventos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgttiposeventos".
 *
 * Columns in table "mzgttiposeventos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTTIPOSEVENTOS
 * @property string $MZGTTIPOSEVENTOS_DESCRIPCION
 * @property string $MZGTTIPOSEVENTOS_CODIGO
 *
 */
abstract class BaseMzgttiposeventos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgttiposeventos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgttiposeventos|Mzgttiposeventoses', $n);
	}

	public static function representingColumn() {
		return 'MZGTTIPOSEVENTOS_DESCRIPCION';
	}

	public function rules() {
		return array(
			array('MZGTTIPOSEVENTOS_DESCRIPCION', 'length', 'max'=>255),
			array('MZGTTIPOSEVENTOS_CODIGO', 'length', 'max'=>50),
			array('MZGTTIPOSEVENTOS_DESCRIPCION, MZGTTIPOSEVENTOS_CODIGO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTTIPOSEVENTOS, MZGTTIPOSEVENTOS_DESCRIPCION, MZGTTIPOSEVENTOS_CODIGO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTTIPOSEVENTOS' => Yii::t('app', 'Pk Mzgttiposeventos'),
			'MZGTTIPOSEVENTOS_DESCRIPCION' => Yii::t('app', 'Mzgttiposeventos Descripcion'),
			'MZGTTIPOSEVENTOS_CODIGO' => Yii::t('app', 'Mzgttiposeventos Codigo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTTIPOSEVENTOS', $this->PK_MZGTTIPOSEVENTOS);
		$criteria->compare('MZGTTIPOSEVENTOS_DESCRIPCION', $this->MZGTTIPOSEVENTOS_DESCRIPCION, true);
		$criteria->compare('MZGTTIPOSEVENTOS_CODIGO', $this->MZGTTIPOSEVENTOS_CODIGO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}