<?php

/**
 * This is the model base class for the table "mzgtproyvincsoci".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtproyvincsoci".
 *
 * Columns in table "mzgtproyvincsoci" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTPROYVINCSOCI
 * @property integer $FK1_MZGTPROYVINCSOCI_INV_MZGTINSTITUCIONES_PK
 * @property integer $FK2_MZGTPROYVINCSOCI_INV_MZGTCINEAMPL_PK
 * @property integer $FK3_MZGTPROYVINCSOCI_INV_MZGTCINEESPC_PK
 * @property integer $FK4_MZGTPROYVINCSOCI_INV_MZGTALCANCES_PK
 * @property string $MZGTPROYVINCSOCI_NOMBRE
 * @property string $MZGTPROYVINCSOCI_MONTO
 * @property string $MZGTPROYVINCSOCI_FECHAINICIO
 * @property string $MZGTPROYVINCSOCI_FECHAFIN
 * @property string $MZGTPROYVINCSOCI_NUMDOC
 * @property string $MZGTPROYVINCSOCI_NUMEST
 *
 */
abstract class BaseMzgtproyvincsoci extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtproyvincsoci';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtproyvincsoci|Mzgtproyvincsocis', $n);
	}

	public static function representingColumn() {
		return 'MZGTPROYVINCSOCI_NOMBRE';
	}

	public function rules() {
		return array(
			array('FK1_MZGTPROYVINCSOCI_INV_MZGTINSTITUCIONES_PK, FK2_MZGTPROYVINCSOCI_INV_MZGTCINEAMPL_PK, FK3_MZGTPROYVINCSOCI_INV_MZGTCINEESPC_PK, FK4_MZGTPROYVINCSOCI_INV_MZGTALCANCES_PK', 'numerical', 'integerOnly'=>true),
			array('MZGTPROYVINCSOCI_NOMBRE', 'length', 'max'=>255),
			array('MZGTPROYVINCSOCI_MONTO', 'length', 'max'=>200),
			array('MZGTPROYVINCSOCI_NUMDOC, MZGTPROYVINCSOCI_NUMEST', 'length', 'max'=>100),
			array('MZGTPROYVINCSOCI_FECHAINICIO, MZGTPROYVINCSOCI_FECHAFIN', 'safe'),
			array('FK1_MZGTPROYVINCSOCI_INV_MZGTINSTITUCIONES_PK, FK2_MZGTPROYVINCSOCI_INV_MZGTCINEAMPL_PK, FK3_MZGTPROYVINCSOCI_INV_MZGTCINEESPC_PK, FK4_MZGTPROYVINCSOCI_INV_MZGTALCANCES_PK, MZGTPROYVINCSOCI_NOMBRE, MZGTPROYVINCSOCI_MONTO, MZGTPROYVINCSOCI_FECHAINICIO, MZGTPROYVINCSOCI_FECHAFIN, MZGTPROYVINCSOCI_NUMDOC, MZGTPROYVINCSOCI_NUMEST', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTPROYVINCSOCI, FK1_MZGTPROYVINCSOCI_INV_MZGTINSTITUCIONES_PK, FK2_MZGTPROYVINCSOCI_INV_MZGTCINEAMPL_PK, FK3_MZGTPROYVINCSOCI_INV_MZGTCINEESPC_PK, FK4_MZGTPROYVINCSOCI_INV_MZGTALCANCES_PK, MZGTPROYVINCSOCI_NOMBRE, MZGTPROYVINCSOCI_MONTO, MZGTPROYVINCSOCI_FECHAINICIO, MZGTPROYVINCSOCI_FECHAFIN, MZGTPROYVINCSOCI_NUMDOC, MZGTPROYVINCSOCI_NUMEST', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTPROYVINCSOCI' => Yii::t('app', 'Pk Mzgtproyvincsoci'),
			'FK1_MZGTPROYVINCSOCI_INV_MZGTINSTITUCIONES_PK' => Yii::t('app', 'Fk1 Mzgtproyvincsoci Inv Mzgtinstituciones Pk'),
			'FK2_MZGTPROYVINCSOCI_INV_MZGTCINEAMPL_PK' => Yii::t('app', 'Fk2 Mzgtproyvincsoci Inv Mzgtcineampl Pk'),
			'FK3_MZGTPROYVINCSOCI_INV_MZGTCINEESPC_PK' => Yii::t('app', 'Fk3 Mzgtproyvincsoci Inv Mzgtcineespc Pk'),
			'FK4_MZGTPROYVINCSOCI_INV_MZGTALCANCES_PK' => Yii::t('app', 'Fk4 Mzgtproyvincsoci Inv Mzgtalcances Pk'),
			'MZGTPROYVINCSOCI_NOMBRE' => Yii::t('app', 'Mzgtproyvincsoci Nombre'),
			'MZGTPROYVINCSOCI_MONTO' => Yii::t('app', 'Mzgtproyvincsoci Monto'),
			'MZGTPROYVINCSOCI_FECHAINICIO' => Yii::t('app', 'Mzgtproyvincsoci Fechainicio'),
			'MZGTPROYVINCSOCI_FECHAFIN' => Yii::t('app', 'Mzgtproyvincsoci Fechafin'),
			'MZGTPROYVINCSOCI_NUMDOC' => Yii::t('app', 'Mzgtproyvincsoci Numdoc'),
			'MZGTPROYVINCSOCI_NUMEST' => Yii::t('app', 'Mzgtproyvincsoci Numest'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTPROYVINCSOCI', $this->PK_MZGTPROYVINCSOCI);
		$criteria->compare('FK1_MZGTPROYVINCSOCI_INV_MZGTINSTITUCIONES_PK', $this->FK1_MZGTPROYVINCSOCI_INV_MZGTINSTITUCIONES_PK);
		$criteria->compare('FK2_MZGTPROYVINCSOCI_INV_MZGTCINEAMPL_PK', $this->FK2_MZGTPROYVINCSOCI_INV_MZGTCINEAMPL_PK);
		$criteria->compare('FK3_MZGTPROYVINCSOCI_INV_MZGTCINEESPC_PK', $this->FK3_MZGTPROYVINCSOCI_INV_MZGTCINEESPC_PK);
		$criteria->compare('FK4_MZGTPROYVINCSOCI_INV_MZGTALCANCES_PK', $this->FK4_MZGTPROYVINCSOCI_INV_MZGTALCANCES_PK);
		$criteria->compare('MZGTPROYVINCSOCI_NOMBRE', $this->MZGTPROYVINCSOCI_NOMBRE, true);
		$criteria->compare('MZGTPROYVINCSOCI_MONTO', $this->MZGTPROYVINCSOCI_MONTO, true);
		$criteria->compare('MZGTPROYVINCSOCI_FECHAINICIO', $this->MZGTPROYVINCSOCI_FECHAINICIO, true);
		$criteria->compare('MZGTPROYVINCSOCI_FECHAFIN', $this->MZGTPROYVINCSOCI_FECHAFIN, true);
		$criteria->compare('MZGTPROYVINCSOCI_NUMDOC', $this->MZGTPROYVINCSOCI_NUMDOC, true);
		$criteria->compare('MZGTPROYVINCSOCI_NUMEST', $this->MZGTPROYVINCSOCI_NUMEST, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}