<?php

/**
 * This is the model base class for the table "mzgtcampus_departamentos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MzgtcampusDepartamentos".
 *
 * Columns in table "mzgtcampus_departamentos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTCAMPUS
 * @property integer $PK_MZGTDEPARTAMENTOS
 *
 */
abstract class BaseMzgtcampusDepartamentos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtcampus_departamentos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MzgtcampusDepartamentos|MzgtcampusDepartamentoses', $n);
	}

	public static function representingColumn() {
		return array(
			'PK_MZGTCAMPUS',
			'PK_MZGTDEPARTAMENTOS',
		);
	}

	public function rules() {
		return array(
			array('PK_MZGTCAMPUS, PK_MZGTDEPARTAMENTOS', 'required'),
			array('PK_MZGTCAMPUS, PK_MZGTDEPARTAMENTOS', 'numerical', 'integerOnly'=>true),
			array('PK_MZGTCAMPUS, PK_MZGTDEPARTAMENTOS', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTCAMPUS' => null,
			'PK_MZGTDEPARTAMENTOS' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTCAMPUS', $this->PK_MZGTCAMPUS);
		$criteria->compare('PK_MZGTDEPARTAMENTOS', $this->PK_MZGTDEPARTAMENTOS);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}