<?php

/**
 * This is the model base class for the table "mzgtparametros".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtparametros".
 *
 * Columns in table "mzgtparametros" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_PARAMETROS
 * @property integer $PK_MZGTEVENTOS
 * @property integer $PK_MZGTPUBLICACIONES
 * @property string $MZGTPARAMETROS_CARRERA
 * @property string $MZGTPARAMETROS_DEPARTAMENTO
 * @property string $MZGTPARAMETROS_FECHAINICIO
 * @property string $MZGTPARAMETROS_FECHAFIN
 * @property integer $PK_MZGTTIPOSEVENTOS
 * @property integer $PK_MZGTTIPOSPUBLICACIONES
 *
 */
abstract class BaseMzgtparametros extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtparametros';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtparametros|Mzgtparametroses', $n);
	}

	public static function representingColumn() {
		return 'MZGTPARAMETROS_CARRERA';
	}

	public function rules() {
		return array(
			array('PK_PARAMETROS, PK_MZGTEVENTOS, PK_MZGTPUBLICACIONES, PK_MZGTTIPOSEVENTOS, PK_MZGTTIPOSPUBLICACIONES', 'required'),
			array('PK_PARAMETROS, PK_MZGTEVENTOS, PK_MZGTPUBLICACIONES, PK_MZGTTIPOSEVENTOS, PK_MZGTTIPOSPUBLICACIONES', 'numerical', 'integerOnly'=>true),
			array('MZGTPARAMETROS_CARRERA, MZGTPARAMETROS_DEPARTAMENTO', 'length', 'max'=>255),
			array('MZGTPARAMETROS_FECHAINICIO, MZGTPARAMETROS_FECHAFIN', 'safe'),
			array('MZGTPARAMETROS_CARRERA, MZGTPARAMETROS_DEPARTAMENTO, MZGTPARAMETROS_FECHAINICIO, MZGTPARAMETROS_FECHAFIN', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_PARAMETROS, PK_MZGTEVENTOS, PK_MZGTPUBLICACIONES, MZGTPARAMETROS_CARRERA, MZGTPARAMETROS_DEPARTAMENTO, MZGTPARAMETROS_FECHAINICIO, MZGTPARAMETROS_FECHAFIN, PK_MZGTTIPOSEVENTOS, PK_MZGTTIPOSPUBLICACIONES', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_PARAMETROS' => Yii::t('app', 'Pk Parametros'),
			'PK_MZGTEVENTOS' => Yii::t('app', 'Pk Mzgteventos'),
			'PK_MZGTPUBLICACIONES' => Yii::t('app', 'Pk Mzgtpublicaciones'),
			'MZGTPARAMETROS_CARRERA' => Yii::t('app', 'Mzgtparametros Carrera'),
			'MZGTPARAMETROS_DEPARTAMENTO' => Yii::t('app', 'Mzgtparametros Departamento'),
			'MZGTPARAMETROS_FECHAINICIO' => Yii::t('app', 'Mzgtparametros Fechainicio'),
			'MZGTPARAMETROS_FECHAFIN' => Yii::t('app', 'Mzgtparametros Fechafin'),
			'PK_MZGTTIPOSEVENTOS' => Yii::t('app', 'Pk Mzgttiposeventos'),
			'PK_MZGTTIPOSPUBLICACIONES' => Yii::t('app', 'Pk Mzgttipospublicaciones'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_PARAMETROS', $this->PK_PARAMETROS);
		$criteria->compare('PK_MZGTEVENTOS', $this->PK_MZGTEVENTOS);
		$criteria->compare('PK_MZGTPUBLICACIONES', $this->PK_MZGTPUBLICACIONES);
		$criteria->compare('MZGTPARAMETROS_CARRERA', $this->MZGTPARAMETROS_CARRERA, true);
		$criteria->compare('MZGTPARAMETROS_DEPARTAMENTO', $this->MZGTPARAMETROS_DEPARTAMENTO, true);
		$criteria->compare('MZGTPARAMETROS_FECHAINICIO', $this->MZGTPARAMETROS_FECHAINICIO, true);
		$criteria->compare('MZGTPARAMETROS_FECHAFIN', $this->MZGTPARAMETROS_FECHAFIN, true);
		$criteria->compare('PK_MZGTTIPOSEVENTOS', $this->PK_MZGTTIPOSEVENTOS);
		$criteria->compare('PK_MZGTTIPOSPUBLICACIONES', $this->PK_MZGTTIPOSPUBLICACIONES);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}