<?php

/**
 * This is the model base class for the table "mzgtproyectos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtproyectos".
 *
 * Columns in table "mzgtproyectos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTPROYECTOS
 * @property string $MZGTPROYECTOS_NOMBRE
 * @property string $MZGTPROYECTOS_CODIGO
 *
 */
abstract class BaseMzgtproyectos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtproyectos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtproyectos|Mzgtproyectoses', $n);
	}

	public static function representingColumn() {
		return 'MZGTPROYECTOS_NOMBRE';
	}

	public function rules() {
		return array(
			array('MZGTPROYECTOS_CODIGO', 'length', 'max'=>255),
			array('MZGTPROYECTOS_NOMBRE', 'safe'),
			array('MZGTPROYECTOS_NOMBRE, MZGTPROYECTOS_CODIGO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTPROYECTOS, MZGTPROYECTOS_NOMBRE, MZGTPROYECTOS_CODIGO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTPROYECTOS' => Yii::t('app', 'Pk Mzgtproyectos'),
			'MZGTPROYECTOS_NOMBRE' => Yii::t('app', 'Mzgtproyectos Nombre'),
			'MZGTPROYECTOS_CODIGO' => Yii::t('app', 'Mzgtproyectos Codigo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTPROYECTOS', $this->PK_MZGTPROYECTOS);
		$criteria->compare('MZGTPROYECTOS_NOMBRE', $this->MZGTPROYECTOS_NOMBRE, true);
		$criteria->compare('MZGTPROYECTOS_CODIGO', $this->MZGTPROYECTOS_CODIGO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}