<?php

/**
 * This is the model base class for the table "mzgtbasesdatosindexada".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtbasesdatosindexada".
 *
 * Columns in table "mzgtbasesdatosindexada" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTBASESDATOSINDEXADA
 * @property string $MZGTBASESDATOSINDEXADA_DESCRIPCION
 * @property string $MZGTBASESDATOSINDEXADA_CODIGO
 *
 */
abstract class BaseMzgtbasesdatosindexada extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtbasesdatosindexada';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtbasesdatosindexada|Mzgtbasesdatosindexadas', $n);
	}

	public static function representingColumn() {
		return 'MZGTBASESDATOSINDEXADA_DESCRIPCION';
	}

	public function rules() {
		return array(
			array('MZGTBASESDATOSINDEXADA_DESCRIPCION', 'length', 'max'=>255),
			array('MZGTBASESDATOSINDEXADA_CODIGO', 'length', 'max'=>50),
			array('MZGTBASESDATOSINDEXADA_DESCRIPCION, MZGTBASESDATOSINDEXADA_CODIGO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTBASESDATOSINDEXADA, MZGTBASESDATOSINDEXADA_DESCRIPCION, MZGTBASESDATOSINDEXADA_CODIGO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTBASESDATOSINDEXADA' => Yii::t('app', 'Pk Mzgtbasesdatosindexada'),
			'MZGTBASESDATOSINDEXADA_DESCRIPCION' => Yii::t('app', 'Mzgtbasesdatosindexada Descripcion'),
			'MZGTBASESDATOSINDEXADA_CODIGO' => Yii::t('app', 'Mzgtbasesdatosindexada Codigo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTBASESDATOSINDEXADA', $this->PK_MZGTBASESDATOSINDEXADA);
		$criteria->compare('MZGTBASESDATOSINDEXADA_DESCRIPCION', $this->MZGTBASESDATOSINDEXADA_DESCRIPCION, true);
		$criteria->compare('MZGTBASESDATOSINDEXADA_CODIGO', $this->MZGTBASESDATOSINDEXADA_CODIGO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}