<?php

/**
 * This is the model base class for the table "mzgtdepartamentos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtdepartamentos".
 *
 * Columns in table "mzgtdepartamentos" available as properties of the model,
 * followed by relations of table "mzgtdepartamentos" available as properties of the model.
 *
 * @property integer $PK_MZGTDEPARTAMENTOS
 * @property string $MZGTDEPARTAMENTOS_NOMBRE
 * @property string $MZGTDEPARTAMENTOS_BANNER
 * @property integer $MZGTDEPARTAMENTOS_ESTADO
 *
 * @property Mzgtcampus[] $mzgtcampuses
 * @property Mzgtcarreras[] $mzgtcarrerases
 */
abstract class BaseMzgtdepartamentos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtdepartamentos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtdepartamentos|Mzgtdepartamentoses', $n);
	}

	public static function representingColumn() {
		return 'MZGTDEPARTAMENTOS_NOMBRE';
	}

	public function rules() {
		return array(
			array('MZGTDEPARTAMENTOS_NOMBRE, MZGTDEPARTAMENTOS_BANNER, MZGTDEPARTAMENTOS_ESTADO', 'required'),
			array('MZGTDEPARTAMENTOS_ESTADO', 'numerical', 'integerOnly'=>true),
			array('MZGTDEPARTAMENTOS_NOMBRE', 'length', 'max'=>200),
			array('MZGTDEPARTAMENTOS_BANNER', 'length', 'max'=>10),
			array('PK_MZGTDEPARTAMENTOS, MZGTDEPARTAMENTOS_NOMBRE, MZGTDEPARTAMENTOS_BANNER, MZGTDEPARTAMENTOS_ESTADO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mzgtcampuses' => array(self::MANY_MANY, 'Mzgtcampus', 'mzgtcampus_departamentos(PK_MZGTDEPARTAMENTOS, PK_MZGTCAMPUS)'),
			'mzgtcarrerases' => array(self::MANY_MANY, 'Mzgtcarreras', 'mzgtdepartamentos_carreras(PK_MZGTDEPARTAMENTOS, PK_MZGTCARRERAS)'),
		);
	}

	public function pivotModels() {
		return array(
			'mzgtcampuses' => 'MzgtcampusDepartamentos',
			'mzgtcarrerases' => 'MzgtdepartamentosCarreras',
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTDEPARTAMENTOS' => Yii::t('app', 'Pk Mzgtdepartamentos'),
			'MZGTDEPARTAMENTOS_NOMBRE' => Yii::t('app', 'Mzgtdepartamentos Nombre'),
			'MZGTDEPARTAMENTOS_BANNER' => Yii::t('app', 'Mzgtdepartamentos Banner'),
			'MZGTDEPARTAMENTOS_ESTADO' => Yii::t('app', 'Mzgtdepartamentos Estado'),
			'mzgtcampuses' => null,
			'mzgtcarrerases' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTDEPARTAMENTOS', $this->PK_MZGTDEPARTAMENTOS);
		$criteria->compare('MZGTDEPARTAMENTOS_NOMBRE', $this->MZGTDEPARTAMENTOS_NOMBRE, true);
		$criteria->compare('MZGTDEPARTAMENTOS_BANNER', $this->MZGTDEPARTAMENTOS_BANNER, true);
		$criteria->compare('MZGTDEPARTAMENTOS_ESTADO', $this->MZGTDEPARTAMENTOS_ESTADO);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}