<?php

/**
 * This is the model base class for the table "mzgtcampespecificoscine".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtcampdetalladocine".
 *
 * Columns in table "mzgtcampespecificoscine" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $FK1CAMPDETALLADOCINE
 * @property integer $FK1_MZGTCAMPDETALLADOCINE_INV_MZGTCAMPESPECIFICOSCINE_PK
 * @property string $MZGTCAMPDETALLADOCINE_NOMBRE
 * @property string $MZGTCAMPDETALLADOCINE_CODIGO
 *
 */
abstract class BaseMzgtcampdetalladocine extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtcampdetalladocine';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtcampdetalladocine|Mzgtcampdetalladocines', $n);
	}

	public static function representingColumn() {
		return 'MZGTCAMPDETALLADOCINE_NOMBRE';
	}

	public function rules() {
		return array(
			array('FK1_MZGTCAMPDETALLADOCINE_INV_MZGTCAMPESPECIFICOSCINE_PK', 'numerical', 'integerOnly'=>true),
			array('MZGTCAMPDETALLADOCINE_NOMBRE, MZGTCAMPDETALLADOCINE_CODIGO', 'length', 'max'=>255),
			array('FK1_MZGTCAMPDETALLADOCINE_INV_MZGTCAMPESPECIFICOSCINE_PK, MZGTCAMPDETALLADOCINE_NOMBRE, MZGTCAMPDETALLADOCINE_CODIGO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTCAMPDETALLADOCINE, FK1_MZGTCAMPDETALLADOCINE_INV_MZGTCAMPESPECIFICOSCINE_PK, MZGTCAMPDETALLADOCINE_NOMBRE, MZGTCAMPDETALLADOCINE_CODIGO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTCAMPDETALLADOCINE' => Yii::t('app', 'Pk Mzgtcampdetalladocine'),
			'FK1_MZGTCAMPDETALLADOCINE_INV_MZGTCAMPESPECIFICOSCINE_PK' => Yii::t('app', 'Fk1 Mzgtcampdetalladoscine Inv Mzgtcampespecificoscine Pk'),
			'MZGTCAMPDETALLADOCINE_NOMBRE' => Yii::t('app', 'Mzgtcampdetalladocine Nombre'),
			'MZGTCAMPDETALLADOCINE_CODIGO' => Yii::t('app', 'Mzgtcampdetalladocine Codigo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTCAMPDETALLADOCINE', $this->PK_MZGTCAMPDETALLADOCINE);
		$criteria->compare('FK1_MZGTCAMPDETALLADOCINE_INV_MZGTCAMPESPECIFICOSCINE_PK', $this->FK1_MZGTCAMPDETALLADOCINE_INV_MZGTCAMPESPECIFICOSCINE_PK);
		$criteria->compare('MZGTCAMPDETALLADOCINE_NOMBRE', $this->MZGTCAMPDETALLADOCINE_NOMBRE, true);
		$criteria->compare('MZGTCAMPDETALLADOCINE_CODIGO', $this->MZGTCAMPDETALLADOCINE_CODIGO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}