<?php

/**
 * This is the model base class for the table "mzgtalcances".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mzgtalcances".
 *
 * Columns in table "mzgtalcances" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTALCANCES
 * @property string $MZGTALCANCES_DESCRIPCION
 * @property string $MZGTALCANCES_CODIGO
 *
 */
abstract class BaseMzgtalcances extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtalcances';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mzgtalcances|Mzgtalcances', $n);
	}

	public static function representingColumn() {
		return 'MZGTALCANCES_DESCRIPCION';
	}

	public function rules() {
		return array(
			array('MZGTALCANCES_DESCRIPCION', 'length', 'max'=>255),
			array('MZGTALCANCES_CODIGO', 'length', 'max'=>50),
			array('MZGTALCANCES_DESCRIPCION, MZGTALCANCES_CODIGO', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PK_MZGTALCANCES, MZGTALCANCES_DESCRIPCION, MZGTALCANCES_CODIGO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTALCANCES' => Yii::t('app', 'Pk Mzgtalcances'),
			'MZGTALCANCES_DESCRIPCION' => Yii::t('app', 'Mzgtalcances Descripcion'),
			'MZGTALCANCES_CODIGO' => Yii::t('app', 'Mzgtalcances Codigo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTALCANCES', $this->PK_MZGTALCANCES);
		$criteria->compare('MZGTALCANCES_DESCRIPCION', $this->MZGTALCANCES_DESCRIPCION, true);
		$criteria->compare('MZGTALCANCES_CODIGO', $this->MZGTALCANCES_CODIGO, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}