<?php

/**
 * This is the model base class for the table "mzgtdepartamentos_carreras".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MzgtdepartamentosCarreras".
 *
 * Columns in table "mzgtdepartamentos_carreras" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $PK_MZGTDEPARTAMENTOS
 * @property integer $PK_MZGTCARRERAS
 *
 */
abstract class BaseMzgtdepartamentosCarreras extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mzgtdepartamentos_carreras';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MzgtdepartamentosCarreras|MzgtdepartamentosCarrerases', $n);
	}

	public static function representingColumn() {
		return array(
			'PK_MZGTDEPARTAMENTOS',
			'PK_MZGTCARRERAS',
		);
	}

	public function rules() {
		return array(
			array('PK_MZGTDEPARTAMENTOS, PK_MZGTCARRERAS', 'required'),
			array('PK_MZGTDEPARTAMENTOS, PK_MZGTCARRERAS', 'numerical', 'integerOnly'=>true),
			array('PK_MZGTDEPARTAMENTOS, PK_MZGTCARRERAS', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PK_MZGTDEPARTAMENTOS' => null,
			'PK_MZGTCARRERAS' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PK_MZGTDEPARTAMENTOS', $this->PK_MZGTDEPARTAMENTOS);
		$criteria->compare('PK_MZGTCARRERAS', $this->PK_MZGTCARRERAS);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}