<?php if($reporte!=null){ ?>
<?php foreach($reporte as $data)	{ 
echo $data['FK1_MZGTPUBLICACIONES_INV_MZGTINSTITUCIONES_PK_']."|".
$data['MZGTPUBLICACIONES_CODIGOISSN']."|".
$data['MZGTPUBLICACIONES_CODIGOISBN']."|".
$data['FK4_MZGTPUBLICACIONES_INV_MZGTTIPOSPUBLICACIONES_PK']."|".
$data['MZGTPUBLICACIONES_OTROTIPOSPUBLICACIONES']."|".
//$data['FK5_MZGTPUBLICACIONES_INV_MZGTBASESDATOSINDEXADA_PK']."|".
$data['MZGTPUBLICACIONES_NOMBREREVISTA']."|".
$data['MZGTPUBLICACIONES_NUMEROREVISTA']."|".
$data['MZGTPUBLICACIONES_PAIS']."|".
$data['MZGTPUBLICACIONES_CIUDAD']."|".
$data['MZGTPUBLICACIONES_NOMBREARTICULO']."|".
$data['MZGTPUBLICACIONES_NOMBREEVENTO']."|".
$data['MZGTPUBLICACIONES_FECHAPUBLICACION']."|".
//$data['MZGTPUBLICACIONES_CEDULAAUTOR']."|".
//$data['MZGTPUBLICACIONES_PRIMERNOMBREAUTOR']."|".
//$data['MZGTPUBLICACIONES_SEGUNDONOMBREAUTOR']."|".
//$data['MZGTPUBLICACIONES_APELLIDOPATERNOAUTOR']."|".
//$data['MZGTPUBLICACIONES_APELLIDOMATERNOAUTOR']."|".
//$data['FK6_MZGTPUBLICACIONES_INV_MZGTLINEASINVESTIGACION_PK']."|".
$data['MZGTPUBLICACIONES_DEPARTAMENTO']."|".
$data['MZGTPUBLICACIONES_CARRERA']."|".
$data['MZGTPUBLICACIONES_EVIDENCIA']."|".
$data['FK2_MZGTPUBLICACIONES_INV_MZGTCAMPAMPLIOSCINE_PK']."|".
$data['FK3_MZGTPUBLICACIONES_INV_MZGTCAMPESPECIFICOSCINE_PK']."|".
$data['MZGTPUBLICACIONES_DOI']."\n";
} ?>
<?php } ?>
